language: php
sudo: required
dist: trusty
services: 
  - docker

env:
  - VERSION=platform

matrix:
  include:
    - env: VERSION=platform PHP=5.6
    - env: VERSION=alpine PHP=5.6
    - env: VERSION=platform PHP=7.1
    - env: VERSION=alpine PHP=7.1

install:
  - composer create-project silverstripe/installer ~/src
  - docker run -d --name database --env MYSQL_ALLOW_EMPTY_PASSWORD=true mysql
  - cp examples/_ss_environment.php ~/src/_ss_environment.php

before_script:
  - env | sort
  - cd "${PHP}/${VERSION}"
  - image="brettt89/silverstripe-web:${PHP}-${VERSION}"

script:
  - travis_retry docker build -t "$image" .
  - docker run -d --name web -p 80:80 --link database --volume ~/src:/var/www/html "$image"
  - sleep 5
  - travis_retry curl http://localhost/dev/build

after_script:
  - docker exec web ls -lah
  - docker images
