language: bash
services: 
  - docker
  - composer

env:
  - VERSION=platform

install:
  - composer create-project silverstripe/installer ~/src
  - docker run -d --name database mysql -e MYSQL_ALLOW_EMPTY_PASSWORD=true

before_script:
  - env | sort
  - cd "$VERSION"
  - image="brettt89/silverstripe-web:${VERSION}"
  - image="${image//'/'/-}"

script:
  - travis_retry docker build -t "$image" .
  - docker run -d --name web --link database "$image" -v ~/src:/var/www/html /var/www/html/framework/sake dev/build

after_script:
  - docker images
