version: "3.8"
services:
  sut:
    build: 
      context: ./tests
      dockerfile: Dockerfile.test
    depends_on:
       - silverstripe
       - database
    environment:
       - DISTRO=${DISTRO:-apache}
    volumes:
       - codebase:/src

  silverstripe:
    build: ${BUILD_DIR:-./src/7.4/apache/buster}
    image: ${IMAGE:-brettt89/silverstripe-web:7.4-apache-buster}
    volumes:
       - codebase:${MOUNT_DIR:-/var/www/html}
    depends_on:
      - database

  create-project:
    image: composer
    command: create-project silverstripe/installer . ^${FRAMEWORK:-4} --ignore-platform-reqs --no-install
    volumes:
       - codebase:/app
       - ${COMPOSER_HOME:-~/.composer}:/tmp

  install-project:
    image: composer
    command: install --ignore-platform-reqs
    volumes:
       - codebase:/app
       - ${COMPOSER_HOME:-~/.composer}:/tmp

  database:
    image: mysql:5.7
    environment:
       - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
       - db-data:/var/lib/mysql
volumes:
     db-data:
     codebase: