# Title: Multi Environment Setup Example
# Author: Brett Tasker <brett@silverstripe.com>
#
# Description: This configuration is an example of how you can use this configuration to run multiple websites at the same time
#
# Note: This configuration requires a network named `my-network` to be pre-setup and nginx-proxy to be runnin on that network
# prior to `running composer up -d`
#
version: '3'
services:
  web:
    image: brettt89/silverstripe-web
    working_dir: /var/www
    volumes:
      - .:/var/www/html
    environment:
      - VIRTUAL_HOST=local.dev

  database:
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

volumes:
  db-data:

networks:
  default:
    external:
      name: my-network
